# SPDX-FileCopyrightText: 2025 Discoded <33738298+Discoded@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for a document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1